"""Champs métier persistants : types, bornes et valeurs proposées par l’interface."""

SETTINGS = {'period_mode': {'type': 'str',
                 'choices': ['Toutes les données', 'Année', 'Période personnalisée'],
                 'default': 'Toutes les données'},
 'company_name': {'type': 'str', 'default': ''},
 'company_siret': {'type': 'str', 'default': ''},
 'advisor_name': {'type': 'str', 'default': ''},
 'diagnostic_date': {'type': 'date'},
 'company_address': {'type': 'str', 'default': ''},
 'pv_peak_kwp': {'type': 'float', 'min': 0.1, 'max': 1000.0, 'default': 10.0},
 'pv_tilt': {'type': 'int', 'min': 0, 'max': 90, 'default': 30},
 'orientation_label': {'type': 'str',
                       'choices': ['Sud', 'Sud-Est', 'Est', 'Sud-Ouest', 'Ouest'],
                       'default': 'Sud'},
 'pv_losses': {'type': 'int', 'min': 0, 'max': 35, 'default': 14},
 'hc_range_count': {'type': 'int', 'choices': [1, 2], 'default': 1},
 'electricity_tariff_type': {'type': 'str',
                             'choices': ['Tarif unique', 'HP / HC', 'HP / HC hiver-été'],
                             'default': 'Tarif unique'},
 'annual_subscription_eur': {'type': 'float', 'min': 0.0, 'max': 100000.0, 'default': 300.0},
 'surplus_sale_price_eur_kwh': {'type': 'float', 'min': 0.0, 'max': 5.0, 'default': 0.0761},
 'report_status': {'type': 'str',
                   'choices': ['Brouillon', 'À compléter après rendez-vous', 'Finalisé'],
                   'default': 'Brouillon'},
 'autocalsol_export_year': {'type': 'int', 'min': 1900, 'max': 2200},
 'calendar_year': {'type': 'int', 'min': 1900, 'max': 2200},
 'selected_year': {'type': 'int', 'min': 1900, 'max': 2200},
 'selected_label': {'type': 'str'},
 'manual_coordinates': {'type': 'bool', 'default': False},
 'manual_latitude': {'type': 'float', 'min': -90.0, 'max': 90.0, 'default': 44.8378},
 'manual_longitude': {'type': 'float', 'min': -180.0, 'max': 180.0, 'default': -0.5792},
 'hc1_start': {'type': 'time', 'default': '22:00:00'},
 'hc1_end': {'type': 'time', 'default': '06:00:00'},
 'unique_electricity_price': {'type': 'float', 'min': 0.0, 'max': 5.0, 'default': 0.1842},
 'fixing_type': {'type': 'str',
                 'choices': ['Surimposition',
                             'Bac acier + panneaux',
                             'Bac acier isolé + panneaux',
                             'Lesté en toiture terrasse',
                             'Soudé sur toiture terrasse',
                             'Intégré au bâti',
                             'Installation au sol',
                             'Ombrière'],
                 'default': 'Surimposition'},
 'erp_icpe_surcharge': {'type': 'bool', 'default': False},
 'structural_study_cost': {'type': 'float', 'min': 0.0, 'max': 100000.0, 'default': 2000.0},
 'roof_renovation_enabled': {'type': 'bool', 'default': False},
 'roof_type': {'type': 'str',
               'choices': ['Bac acier isolé',
                           'Bac acier',
                           'Fibrociment',
                           'Tuile',
                           'Ardoise',
                           'Toiture terrasse'],
               'default': 'Bac acier isolé'},
 'roof_area_m2': {'type': 'float', 'min': 0.0, 'max': 100000.0, 'default': 0.0},
 'asbestos_removal_enabled': {'type': 'bool', 'default': False},
 'connection_mode': {'type': 'str',
                     'choices': ['Aucun / inférieur ou égal à 36 kWc',
                                 'Branchement BT avec extension',
                                 'Branchement complet C4',
                                 'Création poste BT-HTA'],
                     'default': 'Aucun / inférieur ou égal à 36 kWc'},
 'public_extension_length_m': {'type': 'float', 'min': 0.0, 'max': 10000.0, 'default': 0.0},
 'apply_enedis_reduction': {'type': 'bool', 'default': True},
 'private_trench_length_m': {'type': 'float', 'min': 0.0, 'max': 10000.0, 'default': 0.0},
 'include_private_hta_post': {'type': 'bool', 'default': False},
 'include_decoupling_cell': {'type': 'bool', 'default': False},
 'other_investment_costs': {'type': 'float', 'min': 0.0, 'max': 10000000.0, 'default': 0.0},
 'grant_amount': {'type': 'float', 'min': 0.0, 'max': 10000000.0, 'default': 0.0},
 'insurance_rate_percent': {'type': 'float', 'min': 0.0, 'max': 2.0, 'default': 0.5},
 'maintenance_eur_kwp': {'type': 'float', 'min': 0.0, 'max': 30.0, 'default': 10.5},
 'inverter_provision_eur_kwp': {'type': 'float', 'min': 0.0, 'max': 15.0, 'default': 3.0},
 'ifer_rate_eur_kwp': {'type': 'float', 'min': 0.0, 'max': 100.0, 'default': 3.542},
 'other_annual_costs': {'type': 'float', 'min': 0.0, 'max': 1000000.0, 'default': 0.0},
 'financial_horizon_years': {'type': 'int', 'min': 5, 'max': 40, 'default': 20},
 'electricity_price_increase_percent': {'type': 'float', 'min': 0.0, 'max': 10.0, 'default': 2.0},
 'surplus_price_increase_percent': {'type': 'float', 'min': -5.0, 'max': 10.0, 'default': 0.0},
 'production_degradation_percent': {'type': 'float', 'min': 0.0, 'max': 2.0, 'default': 0.5},
 'operating_cost_increase_percent': {'type': 'float', 'min': 0.0, 'max': 10.0, 'default': 2.0},
 'discount_rate_percent': {'type': 'float', 'min': 0.0, 'max': 15.0, 'default': 4.0},
 'pma_subscribed_kva': {'type': 'float', 'min': 0.0, 'max': 10000.0, 'default': 36.0},
 'start_date': {'type': 'date'},
 'end_date': {'type': 'date'},
 'hc2_start': {'type': 'time', 'default': '12:30:00'},
 'hc2_end': {'type': 'time', 'default': '14:30:00'},
 'hp_winter_electricity_price': {'type': 'float', 'min': 0.0, 'max': 5.0, 'default': 0.21},
 'hc_winter_electricity_price': {'type': 'float', 'min': 0.0, 'max': 5.0, 'default': 0.16},
 'hp_summer_electricity_price': {'type': 'float', 'min': 0.0, 'max': 5.0, 'default': 0.18},
 'hc_summer_electricity_price': {'type': 'float', 'min': 0.0, 'max': 5.0, 'default': 0.14},
 'note_context': {'type': 'str', 'default': ''},
 'note_profile': {'type': 'str', 'default': ''},
 'note_power': {'type': 'str', 'default': ''},
 'note_tariff': {'type': 'str', 'default': ''},
 'note_investigate': {'type': 'str', 'default': ''},
 'note_recommendations': {'type': 'str', 'default': ''},
 'note_general': {'type': 'str', 'default': ''},
 'note_pv_observations': {'type': 'str', 'default': ''},
 'hp_electricity_price': {'type': 'float', 'min': 0.0, 'max': 5.0, 'default': 0.2},
 'hc_electricity_price': {'type': 'float', 'min': 0.0, 'max': 5.0, 'default': 0.15},
 'note_activity_hours': {'type': 'str', 'default': ''},
 'note_equipment': {'type': 'str', 'default': ''},
 'analysis_mode': {'type': 'str',
                   'choices': ['Analyse énergétique', 'Opportunité photovoltaïque'],
                   'default': 'Analyse énergétique'}}

PV_KEYS = ['pv_peak_kwp',
 'pv_tilt',
 'orientation_label',
 'pv_losses',
 'surplus_sale_price_eur_kwh',
 'selected_label',
 'manual_coordinates',
 'manual_latitude',
 'manual_longitude',
 'fixing_type',
 'erp_icpe_surcharge',
 'structural_study_cost',
 'roof_renovation_enabled',
 'roof_type',
 'roof_area_m2',
 'asbestos_removal_enabled',
 'connection_mode',
 'public_extension_length_m',
 'apply_enedis_reduction',
 'private_trench_length_m',
 'include_private_hta_post',
 'include_decoupling_cell',
 'other_investment_costs',
 'grant_amount',
 'insurance_rate_percent',
 'maintenance_eur_kwp',
 'inverter_provision_eur_kwp',
 'ifer_rate_eur_kwp',
 'other_annual_costs',
 'financial_horizon_years',
 'electricity_price_increase_percent',
 'surplus_price_increase_percent',
 'production_degradation_percent',
 'operating_cost_increase_percent',
 'discount_rate_percent']
